version: '3.9'

services:

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - 1234:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
